# Generated by Django 4.2.6 on 2023-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_users_usersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=1000)),
            ],
        ),
    ]
