# Generated by Django 4.2.6 on 2023-10-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_taskmanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
