# Generated by Django 4.2.6 on 2023-10-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_taskmanage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='status',
            field=models.CharField(choices=[('Completed', 'Complete'), ('In Progress', 'Inprogress'), ('Pending', 'Pend')], default='Pending', max_length=100),
        ),
    ]
